# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger: none
pr: none

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: src/AgentMulder.sln

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: src/AgentMulder.sln
    platform: 'any cpu'
    configuration: release

- task: VSTest@2
  displayName: 'Run tests'
  inputs:
    testAssemblyVer2: |
     **\AgentMulder.*tests.dll
     !**\*TestAdapter.dll
     !**\obj\**

- task: PowerShell@2
  displayName: 'Build nuget'
  inputs:
    targetType: filePath
    filePath: ./src/buildNuget.ps1
    arguments: '-version "$(Version.Major).$(Version.Minor).$(Version.Revision)" -c Release -waveVersionLow $(Wave.Low) -waveVersionHigh $(Wave.High)'

- task: GitHubRelease@0
  displayName: 'Create GitHub release'
  inputs:
    gitHubConnection: 'GitHub - mareklinka'
    repositoryName: ERNICommunity/AgentMulder
    tagSource: manual
    tag: 'Agent-Mulder-$(Version.Major).$(Version.Minor).$(Version.Revision)'
    assets: 'src/nuget/*.nupkg'

- task: DotNetCoreCLI@2
  displayName: 'Push to JetBrains Plugins'
  inputs:
    command: push
    packagesToPush: 'src/nuget/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'JetBrains Plugins'

